[phases.setup]
nixPkgs = ["python311", "ffmpeg", "deno"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.start]
cmds = ["sh -c "uvicorn main:app --host 0.0.0.0 --port $PORT""]